# Generated by Django 5.0.14 on 2026-05-16 01:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_academy_branding_settings_academy_currency_and_more'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyenrollmentsnapshot',
            name='retention_rate',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='SessionUtilizationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('total_occurrences', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('cancelled', models.PositiveIntegerField(default=0)),
                ('total_enrollment_capacity', models.PositiveIntegerField(default=0)),
                ('total_enrolled', models.PositiveIntegerField(default=0)),
                ('utilization_rate', models.FloatField(default=0)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academies.academy')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('academy', 'date')},
            },
        ),
    ]
