# Generated by Django 5.0.14 on 2026-05-13 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_history', to='players.player'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('occurrence', 'player')},
        ),
    ]
