# Generated by Django 5.0.14 on 2026-05-13 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academies', '0001_initial'),
        ('players', '0001_initial'),
        ('academy_sessions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('technique', models.PositiveSmallIntegerField(default=0)),
                ('stamina', models.PositiveSmallIntegerField(default=0)),
                ('teamwork', models.PositiveSmallIntegerField(default=0)),
                ('behavior', models.PositiveSmallIntegerField(default=0)),
                ('performance_notes', models.TextField(blank=True)),
                ('is_visible_to_parent', models.BooleanField(default=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academies.academy')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ratings', to='academy_sessions.sessionoccurrence')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='players.player')),
            ],
            options={
                'unique_together': {('occurrence', 'player', 'coach')},
            },
        ),
    ]
