# Generated by Django 5.0.14 on 2026-05-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_academy_branding_settings_academy_currency_and_more'),
        ('players', '0002_player_email_player_emergency_contact_player_gender_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('academy', 'registration_number')},
        ),
    ]
