# Generated by Django 5.0.14 on 2026-05-16 02:47

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='medical_notes',
            field=apps.common.fields.EncryptedTextField(blank=True),
        ),
    ]
