# Generated by Django 5.0.14 on 2026-05-13 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academies', '0001_initial'),
        ('groups', '0001_initial'),
        ('players', '0001_initial'),
        ('academy_sessions', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='player_groups', to='players.player'),
        ),
        migrations.AddField(
            model_name='group',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='groups', to='academy_sessions.sessionseries'),
        ),
        migrations.AddField(
            model_name='groupcoach',
            name='academy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academies.academy'),
        ),
        migrations.AddField(
            model_name='groupcoach',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupcoach',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='groups.group'),
        ),
        migrations.AlterUniqueTogether(
            name='groupcoach',
            unique_together={('group', 'coach')},
        ),
    ]
