# Generated by Django 5.0.14 on 2026-05-16 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0002_academy_branding_settings_academy_currency_and_more'),
        ('cancellations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('minimum_notice_hours', models.PositiveIntegerField(default=24)),
                ('auto_approve_enabled', models.BooleanField(default=True)),
                ('auto_approve_max_hours', models.PositiveIntegerField(default=48)),
                ('refund_percentage', models.PositiveSmallIntegerField(default=0)),
                ('allow_coach_override', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='academies.academy')),
            ],
            options={
                'verbose_name_plural': 'Cancellation policies',
            },
        ),
    ]
