# Generated by Django 5.0.14 on 2026-05-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='branding_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='academy',
            name='currency',
            field=models.CharField(default='EGP', max_length=3),
        ),
        migrations.AddField(
            model_name='academy',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=5),
        ),
        migrations.AddField(
            model_name='academy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('trialing', 'Trialing'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='academy',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='academy',
            name='timezone',
            field=models.CharField(default='Africa/Cairo', max_length=50),
        ),
    ]
